version: "2"
services:
  chat:
    build: .
    ports:
        - "3000:3000"
    environment:
        - MONGO_URL=mongodb://mongo:27017/admin
        - URL=http://localhost:3000
    volumes:
        - .:/usr/app
    depends_on:
        - mongo
  mongo:
    image: mongo
    logging:
        driver: none
    ports:
    - "27017:27017"
